use std::{
    env,
    fs::{self, File},
    io::Write,
    path::Path,
};
use serde_json::Value;

fn main() -> std::io::Result<()> {
    // Re-run this build script if sample_response.json ever changes:
    println!("cargo:rerun-if-changed=sample_response.json");

    // 1. Read & parse sample_response.json
    let json_str = fs::read_to_string("sample_response.json")
        .expect("Failed to read sample_response.json");
    let v: Value = serde_json::from_str(&json_str)
        .expect("Invalid JSON in sample_response.json");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("sample_response.rs");
    let mut file = File::create(&dest_path)?;

    let mut struct_fields = String::new();
    let mut const_fields = String::new();

    for (key, value) in v.as_object().expect("Expected JSON object").iter() {
        let (rust_type, rust_value) = match value {
            Value::String(s) => ("String", format!("\"{}\".to_string()", s)),
            Value::Bool(b) => ("bool", b.to_string()),
            Value::Number(n) => {
                if n.is_f64() {
                    ("f64", n.to_string())
                } else {
                    ("i64", n.to_string())
                }
            }
            _ => panic!("Unsupported value type for key {}", key),
        };

        struct_fields.push_str(&format!("    pub {}: {},\n", key, rust_type));
        const_fields.push_str(&format!("    {}: {},\n", key, rust_value));
    }

    let generated_code = format!(
        "// @generated by build.rs - do not edit by hand

#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct JSON_SampleResponse {{
{struct_fields}
}}

pub const JSON_SAMPLE_RESPONSE: JSON_SampleResponse = JSON_SampleResponse {{
{const_fields}
}};
",
        struct_fields = struct_fields,
        const_fields = const_fields
    );

    // Print to stdout
    println!("Generated code:\n{}", generated_code);

    // Write to file
    write!(file, "{}", generated_code)?;

    Ok(())
}