//! Shared build-time parsing, validation, and code generation utilities.
//!
//! This module is compiled in both the root crate build script and scaffolded
//! agent build scripts to keep behavior deterministic across both paths.
use std::{
    collections::BTreeMap,
    env,
    error::Error,
    fmt,
    fs::{self, File},
    io::Write,
    path::{Path, PathBuf},
};

use serde_json::{Map, Value};

#[derive(Debug)]
pub enum BuildError {
    Config { path: String, message: String },
    Io { context: String, source: std::io::Error },
    EnvVar {
        name: &'static str,
        source: std::env::VarError,
    },
}

impl BuildError {
    fn config(path: impl Into<String>, message: impl Into<String>) -> Self {
        Self::Config {
            path: path.into(),
            message: message.into(),
        }
    }

    fn io(context: impl Into<String>, source: std::io::Error) -> Self {
        Self::Io {
            context: context.into(),
            source,
        }
    }
}

impl fmt::Display for BuildError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Config { path, message } => write!(f, "Invalid `.agentcfg` at `{path}`: {message}"),
            Self::Io { context, source } => write!(f, "{context}: {source}"),
            Self::EnvVar { name, source } => {
                write!(f, "Missing required environment variable `{name}`: {source}")
            }
        }
    }
}

impl Error for BuildError {
    fn source(&self) -> Option<&(dyn Error + 'static)> {
        match self {
            Self::Config { .. } => None,
            Self::Io { source, .. } => Some(source),
            Self::EnvVar { source, .. } => Some(source),
        }
    }
}

#[derive(Debug, Clone)]
struct ResourceUrl {
    url: String,
    description: String,
}

#[derive(Debug, Clone)]
struct RunStep {
    kind: String,
    program: String,
    args: Vec<String>,
}

#[derive(Debug, Clone)]
struct Action {
    name: String,
    logic: Value,
    run: Vec<RunStep>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
enum FieldType {
    String,
    Boolean,
    Number,
    Integer,
    Array,
}

#[derive(Debug, Clone)]
struct MappedPropertyType {
    rust_type: String,
    field_type: FieldType,
}

#[derive(Debug, Clone)]
struct AgentConfig {
    prompt: String,
    fields: Vec<(String, String)>,
    resource_urls: Vec<ResourceUrl>,
    actions: Vec<Action>,
}

// Shared build module: these symbols are used by cargo-ai's root build script,
// but not by scaffolded agent build scripts that only call `run_agent_codegen`.
#[allow(dead_code)]
#[derive(Debug, Clone, Copy)]
pub struct TemplateSource {
    pub destination: &'static str,
    pub source: &'static str,
}

/// Generates `agent_model.rs` from `.agentcfg` for scaffolded agent builds.
pub fn run_agent_codegen(rerun_paths: &[&str]) -> Result<(), BuildError> {
    for path in rerun_paths {
        println!("cargo:rerun-if-changed={path}");
    }

    let cfg_path = Path::new(".agentcfg");
    let cfg_text = fs::read_to_string(cfg_path)
        .map_err(|err| BuildError::io(format!("Failed to read `{}`", cfg_path.display()), err))?;
    let generated_code = generate_agent_model_from_str(&cfg_text)?;
    write_out_file("agent_model.rs", &generated_code)?;
    Ok(())
}

#[allow(dead_code)]
/// Writes the generated template tuple array used by `agent_builder::project`.
pub fn write_generated_templates(template_sources: &[TemplateSource]) -> Result<(), BuildError> {
    let mut generated = String::new();
    generated.push_str("// Auto-generated by build.rs - do not edit.\n\n");
    generated.push_str("/// Constant array of template files as (path, contents) tuples.\n");
    generated.push_str(&format!(
        "pub const TEMPLATES: [(&str, &str); {}] = [\n",
        template_sources.len()
    ));

    for template in template_sources {
        generated.push_str(&format!(
            "    ({destination:?}, include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/templates/{source}\"))),\n",
            destination = template.destination,
            source = template.source
        ));
    }
    generated.push_str("];\n");

    write_out_file(".generated_templates.rs", &generated)
}

/// Parses `.agentcfg` JSON and renders strongly-typed Rust agent model code.
pub fn generate_agent_model_from_str(json_str: &str) -> Result<String, BuildError> {
    let root: Value = serde_json::from_str(json_str)
        .map_err(|err| BuildError::config("$", format!("invalid JSON syntax: {err}")))?;
    let parsed = parse_agent_config(&root)?;
    Ok(render_agent_model(&parsed))
}

fn write_out_file(file_name: &str, contents: &str) -> Result<(), BuildError> {
    let out_dir = resolve_out_dir()?;
    let out_path = out_dir.join(file_name);
    let mut file = File::create(&out_path)
        .map_err(|err| BuildError::io(format!("Failed to create `{}`", out_path.display()), err))?;
    file.write_all(contents.as_bytes())
        .map_err(|err| BuildError::io(format!("Failed to write `{}`", out_path.display()), err))
}

fn resolve_out_dir() -> Result<PathBuf, BuildError> {
    env::var("OUT_DIR")
        .map(PathBuf::from)
        .map_err(|source| BuildError::EnvVar {
            name: "OUT_DIR",
            source,
        })
}

fn parse_agent_config(root: &Value) -> Result<AgentConfig, BuildError> {
    let root_obj = expect_object(root, "$")?;

    let prompt = get_required_string(root_obj, "prompt", "$")?.to_string();

    let schema = get_required_object(root_obj, "agent_schema", "$")?;
    let schema_type = get_required_string(schema, "type", "$.agent_schema")?;
    if schema_type != "object" {
        return Err(BuildError::config(
            "$.agent_schema.type",
            format!("expected `object`, got `{schema_type}`"),
        ));
    }
    let properties = get_required_object(schema, "properties", "$.agent_schema")?;

    let mut schema_field_types: BTreeMap<String, FieldType> = BTreeMap::new();
    let mut fields = Vec::with_capacity(properties.len());
    for (name, prop_value) in properties {
        validate_rust_identifier(name, &format!("$.agent_schema.properties.{name}"))?;
        let prop_obj = expect_object(prop_value, &format!("$.agent_schema.properties.{name}"))?;
        let mapped_type =
            map_property_type(prop_obj, &format!("$.agent_schema.properties.{name}"))?;
        schema_field_types.insert(name.clone(), mapped_type.field_type);
        fields.push((name.clone(), mapped_type.rust_type));
    }

    let resource_urls = parse_resource_urls(root_obj)?;
    let actions = parse_actions(root_obj, &schema_field_types)?;

    Ok(AgentConfig {
        prompt,
        fields,
        resource_urls,
        actions,
    })
}

fn parse_resource_urls(root_obj: &Map<String, Value>) -> Result<Vec<ResourceUrl>, BuildError> {
    let urls = get_required_array(root_obj, "resource_urls", "$")?;
    let mut parsed = Vec::with_capacity(urls.len());

    for (index, entry) in urls.iter().enumerate() {
        let path = format!("$.resource_urls[{index}]");
        let entry_obj = expect_object(entry, &path)?;
        let url = get_required_string(entry_obj, "url", &path)?.to_string();
        let description = get_required_string(entry_obj, "description", &path)?.to_string();
        parsed.push(ResourceUrl { url, description });
    }

    Ok(parsed)
}

fn parse_actions(
    root_obj: &Map<String, Value>,
    schema_field_types: &BTreeMap<String, FieldType>,
) -> Result<Vec<Action>, BuildError> {
    let actions = get_required_array(root_obj, "actions", "$")?;
    let mut parsed = Vec::with_capacity(actions.len());

    for (action_idx, action_value) in actions.iter().enumerate() {
        let action_path = format!("$.actions[{action_idx}]");
        let action_obj = expect_object(action_value, &action_path)?;

        let name = get_required_string(action_obj, "name", &action_path)?.to_string();
        let logic = get_required_field(action_obj, "logic", &action_path)?.clone();
        validate_logic_expression(
            &logic,
            &format!("{action_path}.logic"),
            schema_field_types,
        )?;

        let runs = get_required_array(action_obj, "run", &action_path)?;
        let mut run_steps = Vec::with_capacity(runs.len());
        for (run_idx, run_value) in runs.iter().enumerate() {
            let run_path = format!("{action_path}.run[{run_idx}]");
            let run_obj = expect_object(run_value, &run_path)?;

            let kind = get_required_string(run_obj, "kind", &run_path)?.to_string();
            if kind != "exec" {
                return Err(BuildError::config(
                    format!("{run_path}.kind"),
                    format!("unsupported kind `{kind}` (supported: `exec`)"),
                ));
            }

            let program = get_required_string(run_obj, "program", &run_path)?.to_string();
            if program.trim().is_empty() {
                return Err(BuildError::config(
                    format!("{run_path}.program"),
                    "must be a non-empty string",
                ));
            }

            let args = get_required_array(run_obj, "args", &run_path)?
                .iter()
                .enumerate()
                .map(|(arg_idx, arg)| {
                    arg.as_str().map(|s| s.to_string()).ok_or_else(|| {
                        BuildError::config(
                            format!("{run_path}.args[{arg_idx}]"),
                            "expected a string argument",
                        )
                    })
                })
                .collect::<Result<Vec<_>, _>>()?;

            run_steps.push(RunStep {
                kind,
                program,
                args,
            });
        }

        parsed.push(Action {
            name,
            logic,
            run: run_steps,
        });
    }

    Ok(parsed)
}

fn validate_logic_expression(
    value: &Value,
    path: &str,
    schema_field_types: &BTreeMap<String, FieldType>,
) -> Result<(), BuildError> {
    match value {
        Value::Object(map) => {
            if map.is_empty() {
                return Err(BuildError::config(
                    path,
                    "expected a non-empty JSON Logic object",
                ));
            }

            if map.len() != 1 {
                return Err(BuildError::config(
                    path,
                    "expected a JSON Logic object with exactly one operator key",
                ));
            }

            let Some((operator, arguments)) = map.iter().next() else {
                return Err(BuildError::config(
                    path,
                    "expected a non-empty JSON Logic object",
                ));
            };
            if operator.trim().is_empty() {
                return Err(BuildError::config(
                    path,
                    "operator name cannot be empty",
                ));
            }

            if operator == "literal" {
                return Ok(());
            }

            if operator == "var" {
                resolve_var_field_type(arguments, schema_field_types, &format!("{path}.var"))?;
                return Ok(());
            }

            let operator_path = format!("{path}.{operator}");
            validate_logic_arguments(arguments, &operator_path, schema_field_types)?;
            validate_operator_type_constraints(
                operator,
                arguments,
                &operator_path,
                schema_field_types,
            )
        }
        _ => Err(BuildError::config(
            path,
            "expected a JSON Logic object expression",
        )),
    }
}

fn validate_logic_arguments(
    value: &Value,
    path: &str,
    schema_field_types: &BTreeMap<String, FieldType>,
) -> Result<(), BuildError> {
    match value {
        Value::Array(items) => {
            for (idx, item) in items.iter().enumerate() {
                if item.is_object() {
                    validate_logic_expression(item, &format!("{path}[{idx}]"), schema_field_types)?;
                }
            }
            Ok(())
        }
        Value::Object(_) => validate_logic_expression(value, path, schema_field_types),
        _ => Ok(()),
    }
}

fn validate_operator_type_constraints(
    operator: &str,
    arguments: &Value,
    operator_path: &str,
    schema_field_types: &BTreeMap<String, FieldType>,
) -> Result<(), BuildError> {
    if !matches!(operator, "==" | "!=" | ">" | ">=" | "<" | "<=") {
        return Ok(());
    }

    let operands = arguments
        .as_array()
        .ok_or_else(|| BuildError::config(operator_path, "expected an array of operands"))?;

    if operands.len() != 2 {
        return Err(BuildError::config(
            operator_path,
            "expected exactly two operands",
        ));
    }

    let left_path = format!("{operator_path}[0]");
    let right_path = format!("{operator_path}[1]");

    let left = infer_logic_value_type(&operands[0], schema_field_types, &left_path)?;
    let right = infer_logic_value_type(&operands[1], schema_field_types, &right_path)?;

    match operator {
        ">" | ">=" | "<" | "<=" => {
            if !is_numeric_type(&left) {
                return Err(BuildError::config(
                    left_path,
                    "expected a numeric operand for comparison",
                ));
            }
            if !is_numeric_type(&right) {
                return Err(BuildError::config(
                    right_path,
                    "expected a numeric operand for comparison",
                ));
            }
        }
        "==" | "!=" => {
            if !are_compatible_types(&left, &right) {
                return Err(BuildError::config(
                    operator_path,
                    format!(
                        "incompatible operand types for `{operator}` ({}, {})",
                        type_name(&left),
                        type_name(&right)
                    ),
                ));
            }
        }
        _ => {}
    }

    Ok(())
}

fn infer_logic_value_type(
    value: &Value,
    schema_field_types: &BTreeMap<String, FieldType>,
    path: &str,
) -> Result<FieldType, BuildError> {
    match value {
        Value::String(_) => Ok(FieldType::String),
        Value::Bool(_) => Ok(FieldType::Boolean),
        Value::Number(n) => {
            if n.is_i64() || n.is_u64() {
                Ok(FieldType::Integer)
            } else {
                Ok(FieldType::Number)
            }
        }
        Value::Array(_) => Ok(FieldType::Array),
        Value::Null => Err(BuildError::config(path, "null operands are not supported here")),
        Value::Object(map) => {
            if map.len() != 1 {
                return Err(BuildError::config(
                    path,
                    "expected a JSON Logic object with exactly one operator key",
                ));
            }

            let Some((operator, arguments)) = map.iter().next() else {
                return Err(BuildError::config(
                    path,
                    "expected a JSON Logic object with exactly one operator key",
                ));
            };
            if operator == "var" {
                return resolve_var_field_type(
                    arguments,
                    schema_field_types,
                    &format!("{path}.var"),
                );
            }

            if matches!(operator.as_str(), "==" | "!=" | ">" | ">=" | "<" | "<=") {
                validate_operator_type_constraints(
                    operator,
                    arguments,
                    &format!("{path}.{operator}"),
                    schema_field_types,
                )?;
                return Ok(FieldType::Boolean);
            }

            if matches!(operator.as_str(), "and" | "or" | "!") {
                return Ok(FieldType::Boolean);
            }

            if operator == "literal" {
                return infer_logic_value_type(arguments, schema_field_types, path);
            }

            Ok(FieldType::String)
        }
    }
}

fn resolve_var_field_type(
    arguments: &Value,
    schema_field_types: &BTreeMap<String, FieldType>,
    path: &str,
) -> Result<FieldType, BuildError> {
    let var_name = match arguments {
        Value::String(name) => name.as_str(),
        Value::Array(items) => items
            .first()
            .and_then(|v| v.as_str())
            .ok_or_else(|| BuildError::config(path, "expected first `var` argument to be a string"))?,
        _ => {
            return Err(BuildError::config(
                path,
                "expected `var` arguments as a string or array",
            ))
        }
    };

    if var_name.trim().is_empty() {
        return Err(BuildError::config(path, "variable name cannot be empty"));
    }

    if var_name.contains('.') {
        return Err(BuildError::config(
            path,
            "nested variable paths are not supported; use top-level schema property names",
        ));
    }

    schema_field_types.get(var_name).cloned().ok_or_else(|| {
        BuildError::config(
            path,
            format!(
                "unknown variable `{var_name}`; expected one of: {}",
                schema_field_types.keys().cloned().collect::<Vec<_>>().join(", ")
            ),
        )
    })
}

fn is_numeric_type(field_type: &FieldType) -> bool {
    matches!(field_type, FieldType::Number | FieldType::Integer)
}

fn are_compatible_types(left: &FieldType, right: &FieldType) -> bool {
    left == right || (is_numeric_type(left) && is_numeric_type(right))
}

fn type_name(field_type: &FieldType) -> &'static str {
    match field_type {
        FieldType::String => "string",
        FieldType::Boolean => "boolean",
        FieldType::Number => "number",
        FieldType::Integer => "integer",
        FieldType::Array => "array",
    }
}

fn map_property_type(
    property: &Map<String, Value>,
    path: &str,
) -> Result<MappedPropertyType, BuildError> {
    let schema_type = get_schema_type(property, path)?;
    match schema_type.as_str() {
        "string" => Ok(MappedPropertyType {
            rust_type: "String".to_string(),
            field_type: FieldType::String,
        }),
        "boolean" => Ok(MappedPropertyType {
            rust_type: "bool".to_string(),
            field_type: FieldType::Boolean,
        }),
        "number" => Ok(MappedPropertyType {
            rust_type: "f64".to_string(),
            field_type: FieldType::Number,
        }),
        "integer" => Ok(MappedPropertyType {
            rust_type: "i64".to_string(),
            field_type: FieldType::Integer,
        }),
        "array" => map_array_type(property, path),
        "object" => Err(BuildError::config(
            format!("{path}.type"),
            "nested object fields are not supported yet",
        )),
        other => Err(BuildError::config(
            format!("{path}.type"),
            format!("unsupported schema type `{other}`"),
        )),
    }
}

fn map_array_type(
    property: &Map<String, Value>,
    path: &str,
) -> Result<MappedPropertyType, BuildError> {
    let items_value = get_required_field(property, "items", path)?;
    let items_path = format!("{path}.items");
    let items_obj = expect_object(items_value, &items_path)?;
    let item_type = get_schema_type(items_obj, &items_path)?;

    let primitive = match item_type.as_str() {
        "string" => "String",
        "boolean" => "bool",
        "number" => "f64",
        "integer" => "i64",
        "array" => {
            return Err(BuildError::config(
                format!("{items_path}.type"),
                "nested arrays are not supported yet",
            ));
        }
        "object" => {
            return Err(BuildError::config(
                format!("{items_path}.type"),
                "array items of type `object` are not supported yet",
            ));
        }
        other => {
            return Err(BuildError::config(
                format!("{items_path}.type"),
                format!("unsupported array item schema type `{other}`"),
            ));
        }
    };

    Ok(MappedPropertyType {
        rust_type: format!("Vec<{primitive}>"),
        field_type: FieldType::Array,
    })
}

fn get_schema_type(property: &Map<String, Value>, path: &str) -> Result<String, BuildError> {
    let type_value = get_required_field(property, "type", path)?;
    let type_path = format!("{path}.type");
    match type_value {
        Value::String(schema_type) => Ok(schema_type.clone()),
        Value::Array(_) => Err(BuildError::config(
            type_path,
            "union schema types are not supported yet",
        )),
        _ => Err(BuildError::config(type_path, "expected a string schema type")),
    }
}

fn get_required_field<'a>(
    obj: &'a Map<String, Value>,
    key: &str,
    parent_path: &str,
) -> Result<&'a Value, BuildError> {
    obj.get(key).ok_or_else(|| {
        BuildError::config(
            format!("{parent_path}.{key}"),
            format!("missing required field `{key}`"),
        )
    })
}

fn get_required_string<'a>(
    obj: &'a Map<String, Value>,
    key: &str,
    parent_path: &str,
) -> Result<&'a str, BuildError> {
    let path = format!("{parent_path}.{key}");
    let value = get_required_field(obj, key, parent_path)?;
    value
        .as_str()
        .ok_or_else(|| BuildError::config(path, "expected a string"))
}

fn get_required_array<'a>(
    obj: &'a Map<String, Value>,
    key: &str,
    parent_path: &str,
) -> Result<&'a [Value], BuildError> {
    let path = format!("{parent_path}.{key}");
    let value = get_required_field(obj, key, parent_path)?;
    value
        .as_array()
        .map(Vec::as_slice)
        .ok_or_else(|| BuildError::config(path, "expected an array"))
}

fn get_required_object<'a>(
    obj: &'a Map<String, Value>,
    key: &str,
    parent_path: &str,
) -> Result<&'a Map<String, Value>, BuildError> {
    let path = format!("{parent_path}.{key}");
    let value = get_required_field(obj, key, parent_path)?;
    expect_object(value, &path)
}

fn expect_object<'a>(value: &'a Value, path: &str) -> Result<&'a Map<String, Value>, BuildError> {
    value
        .as_object()
        .ok_or_else(|| BuildError::config(path, "expected an object"))
}

fn validate_rust_identifier(name: &str, path: &str) -> Result<(), BuildError> {
    let mut chars = name.chars();
    let Some(first) = chars.next() else {
        return Err(BuildError::config(path, "field name cannot be empty"));
    };

    if first != '_' && !first.is_ascii_alphabetic() {
        return Err(BuildError::config(
            path,
            format!(
                "field name `{name}` must start with an ASCII letter or underscore for Rust codegen"
            ),
        ));
    }

    if !chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric()) {
        return Err(BuildError::config(
            path,
            format!(
                "field name `{name}` must contain only ASCII letters, digits, or underscores for Rust codegen"
            ),
        ));
    }

    if is_rust_keyword(name) {
        return Err(BuildError::config(
            path,
            format!("field name `{name}` is a reserved Rust keyword"),
        ));
    }

    Ok(())
}

fn is_rust_keyword(name: &str) -> bool {
    matches!(
        name,
        "as"
            | "break"
            | "const"
            | "continue"
            | "crate"
            | "else"
            | "enum"
            | "extern"
            | "false"
            | "fn"
            | "for"
            | "if"
            | "impl"
            | "in"
            | "let"
            | "loop"
            | "match"
            | "mod"
            | "move"
            | "mut"
            | "pub"
            | "ref"
            | "return"
            | "self"
            | "Self"
            | "static"
            | "struct"
            | "super"
            | "trait"
            | "true"
            | "type"
            | "unsafe"
            | "use"
            | "where"
            | "while"
            | "async"
            | "await"
            | "dyn"
            | "union"
            | "abstract"
            | "become"
            | "box"
            | "do"
            | "final"
            | "macro"
            | "override"
            | "priv"
            | "try"
            | "typeof"
            | "unsized"
            | "virtual"
            | "yield"
            | "gen"
    )
}

fn render_agent_model(config: &AgentConfig) -> String {
    let mut struct_fields = String::new();
    for (name, rust_type) in &config.fields {
        struct_fields.push_str(&format!("    pub {name}: {rust_type},\n"));
    }

    let prompt_literal = rust_string_literal(&config.prompt);

    let mut url_list = String::new();
    for url in &config.resource_urls {
        url_list.push_str(&format!(
            "        ResourceUrl {{ url: {url}, description: {description} }},\n",
            url = rust_string_literal(&url.url),
            description = rust_string_literal(&url.description)
        ));
    }

    let mut action_code = String::new();
    for action in &config.actions {
        let logic_json = action.logic.to_string();
        let run_steps = action
            .run
            .iter()
            .map(|run_step| {
                let args = run_step
                    .args
                    .iter()
                    .map(|arg| format!("{}.to_string()", rust_string_literal(arg)))
                    .collect::<Vec<_>>()
                    .join(", ");

                format!(
                    "RunStep {{
                        kind: {}.to_string(),
                        program: {}.to_string(),
                        args: vec![{}],
                    }}",
                    rust_string_literal(&run_step.kind),
                    rust_string_literal(&run_step.program),
                    args
                )
            })
            .collect::<Vec<_>>()
            .join(",");

        action_code.push_str(&format!(
            "Action {{
                name: {}.to_string(),
                logic: serde_json::from_str({}).expect(\"generated action logic must be valid JSON\"),
                run: vec![{}],
            }},",
            rust_string_literal(&action.name),
            rust_string_literal(&logic_json),
            run_steps
        ));
    }

    format!(
        r##"
use schemars::{{JsonSchema, schema_for}};
use serde_json;

#[derive(Clone, Debug, Deserialize, Serialize, JsonSchema)]
pub struct Output {{
{struct_fields}}}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct ResourceUrl {{
    pub url: &'static str,
    pub description: &'static str,
}}

pub fn prompt() -> String {{
    String::from({prompt_literal})
}}

pub fn resource_urls() -> Vec<ResourceUrl> {{
    vec![{url_list}]
}}

/// JSON Schema that defines the expected LLM output structure.
/// Derived from the `Output` struct to ensure single source of truth.
/// Returned as a `serde_json::Value` for direct API use.
pub fn json_schema_value() -> serde_json::Value {{
    let schema = schema_for!(Output);
    let mut v = serde_json::to_value(&schema).expect("Failed to serialize derived schema");

    if let Some(obj) = v.as_object_mut() {{
        // Ensure strictness expected by some providers
        obj.entry("additionalProperties")
            .or_insert(serde_json::Value::Bool(false));

        // Add required array based on properties if not already present
        if let Some(props) = obj.get("properties").and_then(|p| p.as_object()) {{
            let required_fields: Vec<serde_json::Value> =
                props.keys().map(|k| serde_json::Value::String(k.clone())).collect();
            obj.insert("required".to_string(), serde_json::Value::Array(required_fields));
        }}
    }}

    v
}}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct RunStep {{
    kind: String,
    program: String,
    args: Vec<String>,
}}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Action {{
    name: String,
    logic: serde_json::Value,
    run: Vec<RunStep>,
}}

pub fn actions() -> Vec<Action> {{
    vec![
{action_code}    ]
}}
"##,
        struct_fields = struct_fields,
        prompt_literal = prompt_literal,
        url_list = url_list,
        action_code = action_code
    )
}

fn rust_string_literal(value: &str) -> String {
    format!("{value:?}")
}
